apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mezadycqg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mezadycqg-python 
  name: mezadycqg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mezadycqg-python 
